### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by zooool** [Mafiasource/Mafiasource#32]
**Describe the bug**
/install/ loads and works fine, but when I go to /web/ the error log says:
```
2023/09/03 13:29:30 [error] 19747#19747: *117 FastCGI sent in stderr: "PHP message: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mafia.seo' doesn't exist in /var/www/html/public_html/src/Data/SeoDAO.php:43
Stack trace:
#0 /var/www/html/public_html/src/Data/SeoDAO.php(43): PDOStatement->execute()
#1 /var/www/html/public_html/src/Business/SeoService.php(47): src\Data\SeoDAO->getSeoDataByRouteName()
#2 /var/www/html/public_html/src/Controllers/.inc.head.php(21): src\Business\SeoService->getSeoDataByRouteName()
#3 /var/www/html/public_html/src/Controllers/notfound.php(3): require_once('...')
#4 /var/www/html/public_html/web/index.php(127): include_once('...')
#5 {main}" while reading response header from upstream, client: x, server: _, request: "GET /web/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "x"
```

The database is also completely empty.

**To Reproduce**
1. Go to '/web/' after visiting '/install'
2. See error

**Expected behavior**
It should work.

**Desktop (please complete the following information):**
PHP 8.2 with nginx.

**Comment by Mafiasource** [comment]
Hello, when the maffia database is empty try to import the /install/config/clean-database.sql file into it through phpMyAdmin or something similar.

**Comment by zooool** [comment]
> 

Ok thanks that seemed to have worked.
